# Generated by Django 3.2.9 on 2023-08-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('projectimage', models.ImageField(blank=True, default='images/project.jpg', null=True, upload_to='images')),
                ('subtitle', models.CharField(default='By Abash', max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kotha/')),
                ('projectImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webmodels.project')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('postimage', models.ImageField(blank=True, default='images/blog.jpg', null=True, upload_to='images')),
                ('body', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(null=True, to='webmodels.Tag')),
            ],
        ),
    ]
