# Generated by Django 3.2.9 on 2023-08-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProImage',
            new_name='Projectimage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectimage',
            new_name='image',
        ),
    ]
