# Generated by Django 3.2.9 on 2023-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0002_auto_20230816_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='projectImage',
        ),
        migrations.AddField(
            model_name='project',
            name='prjimages',
            field=models.ManyToManyField(null=True, to='webmodels.Projectimage'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project/'),
        ),
    ]
