# Generated by Django 3.2.9 on 2023-08-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0003_auto_20230816_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='prjimages',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='projectImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webmodels.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to='images'),
        ),
    ]
