# Generated by Django 3.2.9 on 2023-08-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0004_auto_20230817_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(upload_to='projectPic/'),
        ),
    ]
