# Generated by Django 3.2.9 on 2023-08-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0005_alter_projectimage_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projectimage',
        ),
    ]
