# Generated by Django 3.2.9 on 2023-08-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0009_post_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
