# Generated by Django 3.2.9 on 2023-08-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0011_blog_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_tag',
        ),
    ]
