# Generated by Django 3.2.9 on 2023-08-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0016_rename_image_project_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
