# Generated by Django 3.2.9 on 2023-09-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmodels', '0018_blog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='mainimage',
            new_name='image',
        ),
    ]
